### ISSUE TITLE
An error occurred while exporting

### ISSUE THREAD

**Issue by Xinshou233** [DarkStarSword/3d-fixes#11]
![9S~%O}05D%{ $8OOJWQWVGL](https://user-images.githubusercontent.com/110499719/182498819-590fa629-7c1b-47ec-8df6-8b95d4f51916.png)

**Comment by Xinshou233** [comment]
Python: Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\blender_3dmigoto.py", line 1456, in execute
    export_3dmigoto(self, context, vb_path, ib_path, fmt_path)
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\blender_3dmigoto.py", line 1101, in export_3dmigoto
    stride = obj['3DMigoto:VBStride']
KeyError: 'bpy_struct[key]: key "3DMigoto:VBStride" not found'

location: <unknown location>:-1

**Comment by arsipsik** [comment]
I'm having the same issue and am not sure how to fix it.

**Comment by DarkStarSword** [comment]
That error usually means that you are trying to export something that was not originally imported with the 3DMigoto Blender plugin, and as such is lacking the custom properties that it needs to be able to format the buffers in the way the game requires.

These custom properties can be inspected in Blender in the object properties tab here:

![image](https://github.com/DarkStarSword/3d-fixes/assets/379749/48b524de-eeb8-490a-83bd-4ab0ae6c932c)

It is not recommended to edit them via that user interface directly though, as some of them can be corrupted by doing so. If you wish to transfer these custom properties to another mesh that wasn't imported from the plugin to allow you to attempt to export it your best bet is to join that mesh with another that was imported with the plugin and verify that the custom properties are present on the joined mesh. If you don't actually want the two meshes joined you can then delete the vertices that belonged to the unwanted mesh.

Note that this alone is no guarantee that your mesh will be exportable or usable by the game, and you might need to make sure that things like the vertex groups and UV layers all match up, but it will hopefully get you one step closer.
