### ISSUE TITLE
Import .ib without .vb

### ISSUE THREAD

**Issue by HalanoSiblee** [DarkStarSword/3d-fixes#14]
hello i've downloaded mod which have .ib models only no .vb
script refuses to import .ib without .vb file how fix this ?

**Comment by DarkStarSword** [comment]
It doesn't make sense to have an index buffer without a vertex buffer. That's like having instructions for a join the dots but with no dots to join.

Maybe the mod is relying on the unaltered vertex buffer from the game? If that is the case you would have to dump that buffer just as you would normally do.
