### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by nashat2004** [DarkStarSword/3d-fixes#17]
when i import ib and vb file it does not look for the fmt making me unable to import

**Comment by DarkStarSword** [comment]
Can you please upload a sample of the files you are trying to import.

Also, are you running the new version of the script (updated a couple of weeks ago I think), or the old one?

**Comment by nashat2004** [comment]
[Uploading New WinRAR ZIP archive.zip…]()
also i downloaded the script yesterday

**Comment by DarkStarSword** [comment]
Doesn't look like that link has worked. Can you try again?

**Comment by nashat2004** [comment]
[Robin.zip](https://github.com/DarkStarSword/3d-fixes/files/12704895/Robin.zip)
here you go

**Comment by DarkStarSword** [comment]
Oh yes, this will be a regression from the multi vertex buffer support. I'll look into adding a backwards compatibility path for this, but for now you can work around it by renaming the .vb file to .vb0

**Comment by nashat2004** [comment]
thank you very much
