### ISSUE TITLE
Unhandled TEXCOORD Dimension : 3

### ISSUE THREAD

**Issue by Hetaneko** [DarkStarSword/3d-fixes#18]
I am trying to mod PGR. I can import some of the files but the ones that i want to mod is not working. Is there any way to fix it ?
`Unhandled TEXCOORD Dimension : 3`
These are the files:
[FrameAnalysis.zip](https://github.com/DarkStarSword/3d-fixes/files/12703851/FrameAnalysis.zip)

**Comment by DarkStarSword** [comment]
TEXCOORD can be anything as far as the game is concerned - might be a UV, might be some arbitrary data. But for Blender it HAS to be a UV coordinate, i.e. it has to have exactly 2 dimensions. The plugin translates 4D TEXCOORDS into two sets of 2D UVs, but doesn't currently have a way to handle 1D or 3D TEXCOORDs.

Best bet is to edit the .txt file and redefine it to a 4D TEXCOORD, e.g. change:

```
element[7]:
  SemanticName: TEXCOORD
  SemanticIndex: 3
  Format: R32G32B32_FLOAT
  InputSlot: 1
  AlignedByteOffset: 64
  InputSlotClass: per-vertex
  InstanceDataStepRate: 0
```

to:

```
element[7]:
  SemanticName: TEXCOORD
  SemanticIndex: 3
  Format: R32G32B32**A32**_FLOAT
  InputSlot: 1
  AlignedByteOffset: 64
  InputSlotClass: per-vertex
  InstanceDataStepRate: 0
```

**Comment by DarkStarSword** [comment]
I closed the ticket, but on second thoughts I'll leave it open until the script has a native way to handle this without requiring editing the .txt file

**Comment by DarkStarSword** [comment]
I've updated the script to handle 1D and 3D TEXCOORDs now. Please grab the latest version and give it a try.

**Comment by Hetaneko** [comment]
I tried and it works! Thank you so much.
