### ISSUE TITLE
blender_3dmigoto.py import issue

### ISSUE THREAD

**Issue by SengeeSama** [DarkStarSword/3d-fixes#6]
I can't import vb.txt and ib.txt using the blender_3dmigoto.py add-on.
It says "Only draw calls using a single vertex buffer and a single index are supported now"

**Comment by Swagsy** [comment]
Because it's not supported yet, wait until the script receives the update for that

**Comment by Tosyk** [comment]
any news on support  multiple buffers?

**Comment by DarkStarSword** [comment]
Support for this is now in the blender_multi_vbs_v3 branch. Consider this beta as it has only been very lightly tested and there is a moderate risk it might have broken something - please let me know if you are able to successfully use it, or run into any problems:

https://github.com/DarkStarSword/3d-fixes/blob/blender_multi_vbs_v3/blender_3dmigoto.py

Apologies that it has taken me so long to get around to this.

**Comment by DarkStarSword** [comment]
Closing this as a duplicate of https://github.com/DarkStarSword/3d-fixes/issues/10
